import Link from "next/link";

const sections = [
  ["1. One-time analysis credits", "SocialOlla sells one-time analysis credits. These credit packs are not subscriptions and do not renew automatically. The price, number of credits, and payment processor are shown before payment."],
  ["2. Free audit", "Eligible verified accounts can receive one free audit. The current free-audit allowance and its limits are shown in the product before you run an audit."],
  ["3. Failed analyses", "If a provider or service failure prevents SocialOlla from completing a paid analysis, SocialOlla attempts to return the consumed analysis credit automatically. A public profile being unavailable, private, deleted, or returning insufficient public data may prevent a report from being created."],
  ["4. Refund requests", "If you believe a credit was used in error, contact us with your audit ID and payment confirmation. We will review the technical delivery record before deciding whether a refund or credit restoration is appropriate."],
  ["5. Payment processing", "Payments are processed by Square. SocialOlla does not store full payment-card information. Square's checkout terms and payment records also apply to a purchase."],
];

export default function CreditPolicyPage() {
  return <main className="min-h-[100dvh] bg-[var(--social-page)] px-5 py-5 text-[var(--social-text)] sm:px-8 lg:px-12"><nav className="so-public-nav mx-auto max-w-3xl"><Link className="font-display text-xl font-extrabold tracking-[-0.04em]" href="/">SocialOlla</Link><Link className="so-public-back" href="/">← Home</Link><Link className="rounded-full bg-[var(--social-blue)] px-4 py-2.5 text-sm font-extrabold text-[var(--social-ink)] transition hover:bg-[#cdbbff]" href="/pricing">View pricing</Link></nav><article className="mx-auto max-w-3xl py-16 lg:py-24"><p className="text-sm font-extrabold text-[var(--social-blue)]">Payments</p><h1 className="mt-4 font-display text-5xl font-extrabold tracking-[-0.04em] sm:text-6xl">Credit and Refund Policy</h1><p className="mt-5 text-lg leading-8 text-[var(--social-muted-on-dark)]">Effective July 20, 2026. Clear rules for one-time SocialOlla analysis credits.</p><div className="mt-12 grid gap-10">{sections.map(([heading, body]) => <section key={heading}><h2 className="text-2xl font-extrabold tracking-[-0.04em]">{heading}</h2><p className="mt-3 leading-7 text-[var(--social-muted-on-dark)]">{body}</p></section>)}</div></article><footer className="mx-auto flex max-w-3xl flex-wrap justify-between gap-4 border-t border-[var(--social-line-dark)] py-8 text-sm font-semibold text-[var(--social-muted-on-dark)]"><Link href="/">SocialOlla</Link><Link className="text-white underline-offset-4 hover:text-[var(--social-blue)] hover:underline" href="/contact">Contact</Link><Link className="text-white underline-offset-4 hover:text-[var(--social-blue)] hover:underline" href="/privacy">Privacy</Link><Link className="text-white underline-offset-4 hover:text-[var(--social-blue)] hover:underline" href="/terms">Terms</Link></footer></main>;
}
