import Link from "next/link";

const sections = [
  ["1. The service", "SocialOlla analyzes publicly available short-form video information and turns it into campaign recommendations. It is a decision-support product, not a guarantee of views, sales, reach, platform distribution, or any other outcome."],
  ["2. Public data boundary", "SocialOlla may use public profile, video, caption, timestamp, visible interaction, transcript, and audio-label data returned by its providers. Public data can be incomplete, changed, removed, or unavailable. SocialOlla does not present public proxies as private platform Insights, reach, watch time, retention, audience demographics, or follower growth."],
  ["3. Accounts and acceptable use", "You are responsible for your account and for the profile URLs you submit. Submit only public content you are authorized to analyze. Do not use the service to violate platform rules, infringe rights, harass others, evade security controls, or submit harmful or unlawful material."],
  ["4. Recommendations and AI output", "Recommendations, hooks, scripts, captions, and scores are generated to help you plan content. Review them before publishing. You remain responsible for your published content, claims, disclosures, permissions, and compliance with applicable law and platform policies."],
  ["5. Credits and payment", "SocialOlla offers one-time analysis credits. A full analysis consumes one credit when you choose to run it. Lifetime access and Monthly access are separate products. When checkout is enabled, prices, renewal terms, and cancellation details are shown before payment. Payments are processed by Square."],
  ["6. Availability and changes", "We may change, pause, or improve the service, providers, supported platforms, and features. We may also update these Terms when the service changes. Continued use after an updated effective date means you accept the updated Terms."],
  ["7. Disclaimers and limits", "The service is provided as available. To the extent permitted by applicable law, SocialOlla disclaims warranties that the service will be uninterrupted, error-free, complete, or fit for a particular purpose. Nothing in these Terms limits rights that cannot be limited under applicable law."],
];

export default function TermsPage() {
  return (
    <main className="min-h-[100dvh] bg-[var(--social-page)] px-5 py-5 text-[var(--social-text)] sm:px-8 lg:px-12">
      <nav className="so-public-nav mx-auto max-w-5xl"><Link className="font-display text-xl font-extrabold tracking-[-0.04em]" href="/">SocialOlla</Link><Link className="so-public-back" href="/">← Home</Link><Link className="rounded-full bg-[var(--social-blue)] px-4 py-2.5 text-sm font-extrabold text-[var(--social-ink)] hover:bg-[#cdbbff]" href="/pricing">View pricing</Link></nav>
      <article className="mx-auto max-w-3xl py-16 lg:py-24"><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--social-blue)]">Legal</p><h1 className="mt-4 text-5xl font-black tracking-[-0.04em] sm:text-6xl">Terms of Service</h1><p className="mt-5 text-lg leading-8 text-[var(--social-muted-on-dark)]">Effective July 20, 2026. These Terms govern your use of SocialOlla.</p><div className="mt-12 grid gap-10">{sections.map(([title, body]) => <section key={title}><h2 className="text-2xl font-black tracking-[-0.04em]">{title}</h2><p className="mt-3 leading-7 text-[var(--social-muted-on-dark)]">{body}</p></section>)}</div><section className="mt-12 rounded-2xl border border-[var(--social-line-dark)] bg-[var(--social-surface)] p-6"><h2 className="text-2xl font-black tracking-[-0.04em]">Questions about a purchase?</h2><p className="mt-3 leading-7 text-[var(--social-muted-on-dark)]">Keep your analysis ID and payment confirmation. Use the support path made available in your SocialOlla account so we can investigate a technical delivery issue.</p></section></article>
      <footer className="mx-auto flex max-w-5xl flex-wrap justify-between gap-4 border-t border-[var(--social-line-dark)] py-8 text-sm font-semibold text-[var(--social-muted-on-dark)]"><Link href="/">SocialOlla</Link><span className="flex gap-4"><Link className="text-white underline-offset-4 hover:text-[var(--social-blue)] hover:underline" href="/pricing">Pricing</Link><Link className="text-white underline-offset-4 hover:text-[var(--social-blue)] hover:underline" href="/contact">Contact</Link><Link className="text-white underline-offset-4 hover:text-[var(--social-blue)] hover:underline" href="/privacy">Privacy</Link><Link className="text-white underline-offset-4 hover:text-[var(--social-blue)] hover:underline" href="/credit-policy">Credits and refunds</Link></span></footer>
    </main>
  );
}
