import Link from "next/link";

const sections = [
  ["1. What this policy covers", "This Privacy Policy explains how SocialOreo handles information when you use the website, create an account, run an audit, or buy audit credits."],
  ["2. Information we process", "This can include the account identifier and email supplied through Auth0; contact-form messages and reply email; public profile URLs; the campaign brief you enter; public social-video data returned by a provider; generated reports; audit records; and Square payment or customer references. SocialOreo does not receive or store your full payment-card number."],
  ["3. Why we use it", "We use this information to run your requested audit, create your report and post plan, maintain your account and credits, answer support messages, secure the service, and improve the product."],
  ["4. Providers that help operate SocialOreo", "SocialOreo uses service providers to deliver the product. Depending on the feature you use, this can include Auth0 for authentication, Square for payment processing, public-data providers for profile analysis, AI providers for analysis generation, and hosting or database providers. These providers process only the information needed for the service they provide."],
  ["5. Public-data and connected-account boundary", "An audit can include data that is publicly visible on a submitted social profile or video. Public availability does not make the data private to SocialOreo; it is used only to create the requested audit and related product functionality. If you separately connect an eligible Instagram professional account through Meta, SocialOreo may process the approved Meta API Insights for that account. SocialOreo labels those values as Meta Insights and does not estimate them from public data."],
  ["6. Your choices", "You can contact us to ask about your account or personal information. You can also avoid submitting a profile or campaign brief that you do not want us to process."],
  ["7. Children", "SocialOreo is not directed to children under 13. Do not create an account or submit personal information if you are under 13."],
];

export default function PrivacyPage() {
  return <PolicyLayout eyebrow="Legal" title="Privacy Policy" subtitle="Effective July 20, 2026. A plain-language explanation of the data SocialOreo uses to provide its audits." sections={sections} />;
}

function PolicyLayout({ eyebrow, title, subtitle, sections }: { eyebrow: string; title: string; subtitle: string; sections: string[][] }) {
  return <main className="min-h-[100dvh] bg-[var(--social-page)] px-5 py-5 text-[var(--social-text)] sm:px-8 lg:px-12"><nav className="so-public-nav mx-auto max-w-3xl"><Link className="font-display text-xl font-extrabold tracking-[-0.04em]" href="/">SocialOreo</Link><Link className="so-public-back" href="/">← Home</Link><Link className="rounded-full bg-[var(--social-blue)] px-4 py-2.5 text-sm font-extrabold text-[var(--social-ink)] transition hover:bg-[#cdbbff]" href="/pricing">View pricing</Link></nav><article className="mx-auto max-w-3xl py-16 lg:py-24"><p className="text-sm font-extrabold text-[var(--social-blue)]">{eyebrow}</p><h1 className="mt-4 font-display text-5xl font-extrabold tracking-[-0.04em] sm:text-6xl">{title}</h1><p className="mt-5 text-lg leading-8 text-[var(--social-muted-on-dark)]">{subtitle}</p><div className="mt-12 grid gap-10">{sections.map(([heading, body]) => <section key={heading}><h2 className="text-2xl font-extrabold tracking-[-0.04em]">{heading}</h2><p className="mt-3 leading-7 text-[var(--social-muted-on-dark)]">{body}</p></section>)}</div></article><footer className="mx-auto flex max-w-3xl flex-wrap justify-between gap-4 border-t border-[var(--social-line-dark)] py-8 text-sm font-semibold text-[var(--social-muted-on-dark)]"><Link href="/">SocialOreo</Link><Link className="text-white underline-offset-4 hover:text-[var(--social-blue)] hover:underline" href="/contact">Contact</Link><Link className="text-white underline-offset-4 hover:text-[var(--social-blue)] hover:underline" href="/terms">Terms</Link><Link className="text-white underline-offset-4 hover:text-[var(--social-blue)] hover:underline" href="/credit-policy">Credit and Refund Policy</Link></footer></main>;
}
